### ISSUE TITLE
Panic when curling _ping over TCP socket (not unix)

### ISSUE THREAD

**Issue by smarterclayton** [projectatomic/docker#167]
**Output of `docker version`:**

```
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-24.gitf476348.fc23.x86_64
 Go version:      go1.5.4
 Git commit:      f476348/1.10.3
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-24.gitf476348.fc23.x86_64
 Go version:      go1.5.4
 Git commit:      f476348/1.10.3
 Built:           
 OS/Arch:         linux/amd64
```

**Steps to reproduce the issue:**
1. Try to connect over TCP (with `docker daemon -H 0.0.0.0:2376`)
2. See panic in the client

```
[8217]: time="2016-06-08T16:12:19.503676158Z" level=info msg="API listen on /var/run/docker.sock"
[8217]: time="2016-06-08T16:12:19.503792363Z" level=info msg="API listen on [::]:2376"
[8217]: 2016/06/08 16:12:27 http: panic serving 10.1.2.2:43562: reflect: call of reflect.Value.Elem on stru
[8217]: goroutine 12 [running]:
[8217]: net/http.(*conn).serve.func1(0xc82000c210, 0x7fb42e72f7b8, 0xc8207ac018)
[8217]: /usr/lib/golang/src/net/http/server.go:1287 +0xb5 fp=0xc8206ff020 sp=0xc8206fef50
[8217]: runtime.call32(0x0, 0x1980108, 0xc820084170, 0x1800000018)
[8217]: /usr/lib/golang/src/runtime/asm_amd64.s:437 +0x3e fp=0xc8206ff048 sp=0xc8206ff020
[8217]: runtime.gopanic(0x13bb180, 0xc82069cba0)
[8217]: /usr/lib/golang/src/runtime/panic.go:423 +0x4e9 fp=0xc8206ff0c8 sp=0xc8206ff048
[8217]: reflect.Value.Elem(0x140cf00, 0xc8207ac018, 0xf9, 0x0, 0x0, 0x0)
[8217]: /usr/lib/golang/src/reflect/value.go:732 +0x21f fp=0xc8206ff118 sp=0xc8206ff0c8
[8217]: github.com/docker/docker/api/server.getFdFromWriter(0x7fb42e72fa08, 0xc82000c2c0, 0x16775d0)
[8217]: /builddir/build/BUILD/docker-f47634855e8b366fcb1739588ac24ffd8488582f/_build/src/github.com/docker/
[8217]: github.com/docker/docker/api/server.(*Server).LogAction(0xc820018900, 0x7fb42e72fa08, 0xc82000c2c0,
[8217]: /builddir/build/BUILD/docker-f47634855e8b366fcb1739588ac24ffd8488582f/_build/src/github.com/docker/
[8217]: github.com/docker/docker/api/server.(*Server).auditMiddleware.func1(0x7fb42e733b38, 0xc820728e70, 0
[8217]: /builddir/build/BUILD/docker-f47634855e8b366fcb1739588ac24ffd8488582f/_build/src/github.com/docker/
[8217]: github.com/docker/docker/api/server.versionMiddleware.func1(0x7fb42e733b38, 0xc820728e70, 0x7fb42e7
[8217]: /builddir/build/BUILD/docker-f47634855e8b366fcb1739588ac24ffd8488582f/_build/src/github.com/docker/
[8217]: github.com/docker/docker/api/server.(*Server).corsMiddleware.func1(0x7fb42e72f580, 0xc820011520, 0x
[8217]: /builddir/build/BUILD/docker-f47634855e8b366fcb1739588ac24ffd8488582f/_build/src/github.com/docker/
[8217]: github.com/docker/docker/api/server.(*Server).userAgentMiddleware.func1(0x7fb42e72f580, 0xc82001152
[8217]: /builddir/build/BUILD/docker-f47634855e8b366fcb1739588ac24ffd8488582f/_build/src/github.com/docker/
[8217]: github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7fb42e72fa08, 0xc82000c2c0, 0
[8217]: /builddir/build/BUILD/docker-f47634855e8b366fcb1739588ac24ffd8488582f/_build/src/github.com/docker/
[8217]: net/http.HandlerFunc.ServeHTTP(0xc820a996a0, 0x7fb42e72fa08, 0xc82000c2c0, 0xc820af8000)
[8217]: /usr/lib/golang/src/net/http/server.go:1422 +0x3a fp=0xc8206ffa98 sp=0xc8206ffa78
[8217]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc8207b4190, 0x7fb42e72fa08, 0xc82000c2c0, 0xc820af8000
[8217]: /builddir/build/BUILD/docker-f47634855e8b366fcb1739588ac24ffd8488582f/vendor/src/github.com/gorilla
[8217]: github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc820adfe30, 0x7fb42e72fa08, 0xc820
[8217]: /builddir/build/BUILD/docker-f47634855e8b366fcb1739588ac24ffd8488582f/_build/src/github.com/docker/
[8217]: net/http.serverHandler.ServeHTTP(0xc820018a80, 0x7fb42e72fa08, 0xc82000c2c0, 0xc820af8000)
[8217]: /usr/lib/golang/src/net/http/server.go:1862 +0x19e fp=0xc8206ffc40 sp=0xc8206ffbe0
[8217]: net/http.(*conn).serve(0xc82000c210)
[8217]: /usr/lib/golang/src/net/http/server.go:1361 +0xbee fp=0xc8206fff98 sp=0xc8206ffc40
[8217]: runtime.goexit()
[8217]: /usr/lib/golang/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc8206fffa0 sp=0xc8206fff98
[8217]: created by net/http.(*Server).Serve
[8217]: /usr/lib/golang/src/net/http/server.go:1910 +0x3f6
```

**Comment by smarterclayton** [comment]
@runcom saw this today on f23 when trying to connect from my Mac - I can reproduce with curl locally against _ping

**Comment by runcom** [comment]
taking care of this, thx @smarterclayton

**Comment by runcom** [comment]
fixed in both fedora and rhel 1.10.3 branches

**Comment by amatsus** [comment]
Could you fix the docker-1.11 and docker-1.12 branches?

**Comment by runcom** [comment]
@amatsus done

**Comment by amatsus** [comment]
@runcom I'm grateful for your prompt handling
